### ISSUE TITLE
Feature: option sudo: true for verifier

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-skeleton#78]
I want to run the verifier with sudo privieleges per default.
This can be achieved with an option.

```
verifier:
  name: testinfra
  options:
    v: 1
    sudo: true
  lint:
    name: flake8
```
